import test from 'node:test';import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createSpeechClient,readRememberedKey,saveRememberedKey,KEY_STORAGE} from '../lib/client-speech.mjs';
import {words} from '../lib/words.mjs';
import {toWav} from '../lib/audio.mjs';
const store=()=>{const map=new Map();return{map,getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)}};
function fakeSdk({hang=false,recognition}={}){const state={closed:0,ssml:'',token:'',pcm:null,telemetry:null};class Recognizer{static enableTelemetry(v){state.telemetry=v;}constructor(c,a){state.config=c;}close(){state.closed++;}recognizeOnceAsync(ok){if(recognition){ok(recognition);return;}if(!hang)ok({reason:2,properties:{getProperty:()=>JSON.stringify({RecognitionStatus:'Success',NBest:[{Confidence:.9,PronunciationAssessment:{AccuracyScore:86}}]})}});}}
 const sdk={SpeechConfig:{fromAuthorizationToken(token,region){state.token=token;state.region=region;return{setProperty(){}};}},SpeechRecognizer:Recognizer,SpeechSynthesizer:class{close(){state.closed++;}speakSsmlAsync(s,ok){state.ssml=s;if(!hang)ok({reason:1,audioData:new Uint8Array([1,2]).buffer});}},OutputFormat:{Detailed:1},PropertyId:{SpeechServiceConnection_EnableAudioLogging:'logging',SpeechServiceResponse_JsonResult:'json'},SpeechSynthesisOutputFormat:{Audio16Khz32KBitRateMonoMp3:1},ResultReason:{NoMatch:0,SynthesizingAudioCompleted:1,RecognizedSpeech:2,Canceled:3},AudioInputStream:{createPushStream(){return{write(b){state.pcm=b;},close(){}}}},AudioStreamFormat:{getWaveFormatPCM:(...args)=>{state.format=args;}},AudioConfig:{fromStreamInput:x=>x},PronunciationAssessmentConfig:class{constructor(...args){state.assessment=args;}applyTo(){}},PronunciationAssessmentGradingSystem:{HundredMark:1},PronunciationAssessmentGranularity:{Word:1,Phoneme:2}};
 return{state,sdk};}
test('key storage is opt-in; forgetting removes it; malformed saved key ignored',()=>{const s=store();assert.equal(readRememberedKey(s),'');saveRememberedKey(s,'a'.repeat(32),false);assert.equal(s.map.size,0);saveRememberedKey(s,'a'.repeat(32),true);assert.equal(readRememberedKey(s),'a'.repeat(32));saveRememberedKey(s,'',false);assert.equal(s.map.size,0);s.setItem(KEY_STORAGE,'invalid');assert.equal(readRememberedKey(s),'');});
test('TTS sends raw key only in Azure token header and passes short token to SDK',async()=>{const {state,sdk}=fakeSdk();const requests=[];const s=store();const client=createSpeechClient({storage:s,loadSdk:async()=>sdk,fetcher:async(url,options)=>{requests.push({url,options});return new Response('short-lived-token');}});const result=await client.say({key:'a'.repeat(32),word:words[10],voice:'Svetlana',slow:true});assert.equal(result.type,'audio/mpeg');assert.equal(requests[0].url,'https://eastus.api.cognitive.microsoft.com/sts/v1.0/issueToken');assert.equal(requests[0].options.headers['Ocp-Apim-Subscription-Key'],'a'.repeat(32));assert.equal(requests[0].options.redirect,'error');assert.equal(requests[0].options.credentials,'omit');assert.equal(state.token,'short-lived-token');assert.equal(state.region,'eastus');assert.equal(state.telemetry,false);assert.match(state.ssml,/rate="-50%"/);assert.equal(state.closed,1);assert.ok(!JSON.stringify([...s.map]).includes('a'.repeat(32)));});
test('assessment uses fixed PCM 16kHz and reference word, disposes recognizer',async()=>{const {state,sdk}=fakeSdk();const client=createSpeechClient({loadSdk:async()=>sdk,fetcher:async()=>new Response('token')});const audio=toWav([Float32Array.from({length:48000},(_,i)=>Math.sin(i)*.1)],48000);const result=await client.assess({key:'a'.repeat(32),word:words[10],audio});assert.equal(result.accuracy,86);assert.equal(state.pcm.byteLength,32000);assert.deepEqual(state.format,[16000,16,1]);assert.equal(state.assessment[0],words[10].text);assert.equal(state.assessment[2],2,'phoneme granularity');assert.equal(state.closed,1);});
test('cancellation closes engine, concurrency guarded, raw provider error never surfaced',async()=>{const {state,sdk}=fakeSdk({hang:true});let started;const ready=new Promise(r=>started=r);const client=createSpeechClient({loadSdk:async()=>sdk,fetcher:async()=>{started();return new Response('token');}});const abort=new AbortController();const active=client.say({key:'a'.repeat(32),word:words[0],signal:abort.signal});await ready;await new Promise(r=>setTimeout(r,0));await assert.rejects(()=>client.say({key:'a'.repeat(32),word:words[0]}),/current/);abort.abort();await assert.rejects(()=>active,/Cancelled/);assert.ok(state.closed>=1);const errorClient=createSpeechClient({loadSdk:async()=>sdk,fetcher:async()=>{throw Error('SECRET_PROVIDER_VALUE')}});await assert.rejects(()=>errorClient.say({key:'a'.repeat(32),word:words[0]}),e=>!e.message.includes('SECRET_PROVIDER_VALUE'));});
test('no local request limit: many calls in a row all reach Azure and nothing is stored',async()=>{const {sdk}=fakeSdk();let requests=0;const s=store();const client=createSpeechClient({storage:s,loadSdk:async()=>sdk,fetcher:async()=>{requests++;return new Response('token')}});for(let i=0;i<75;i++)await client.say({key:'a'.repeat(32),word:words[0]});assert.equal(requests,75);assert.equal(s.map.size,0);});

test('static deployment has no backend, volume, secrets or always-on machines',async()=>{const config=await readFile(new URL('../fly.toml',import.meta.url),'utf8');assert.match(config,/auto_stop_machines = "stop"/);assert.match(config,/min_machines_running = 0/);assert.doesNotMatch(config,/\[\[mounts\]\]|AZURE|SESSION/);const nginx=await readFile(new URL('../nginx.conf',import.meta.url),'utf8');assert.match(nginx,/access_log off/);assert.match(nginx,/location \/api\/ \{ return 404/);assert.match(nginx,/form-action 'none'/);});
test('oversized token and HTTP rejection fail closed before SDK use',async()=>{for(const response of [()=>new Response('x'.repeat(16385)),()=>new Response('provider details',{status:401})]){const {sdk,state}=fakeSdk();const client=createSpeechClient({loadSdk:async()=>sdk,fetcher:async()=>response()});await assert.rejects(()=>client.say({key:'a'.repeat(32),word:words[0]}),/Azure could not finish/);assert.equal(state.token,'');assert.equal(state.ssml,'');}});
test('already cancelled or invalid audio requests never contact Azure',async()=>{let calls=0;const {sdk}=fakeSdk();const client=createSpeechClient({loadSdk:async()=>sdk,fetcher:async()=>{calls++;return new Response('token')}});const abort=new AbortController();abort.abort();await assert.rejects(()=>client.say({key:'a'.repeat(32),word:words[0],signal:abort.signal}),/Cancelled/);await assert.rejects(()=>client.assess({key:'a'.repeat(32),word:words[0],audio:new ArrayBuffer(12)}),/Record/);assert.equal(calls,0);});

const clip=()=>toWav([Float32Array.from({length:48000},(_,i)=>Math.sin(i)*.1)],48000);
test('assessment with no recognised speech asks for a retry instead of reporting an Azure failure',async()=>{const {sdk}=fakeSdk({recognition:{reason:0}});const client=createSpeechClient({loadSdk:async()=>sdk,fetcher:async()=>new Response('token')});const result=await client.assess({key:'a'.repeat(32),word:words[10],audio:clip()});assert.equal(result.kind,'uncertain');assert.match(result.message,/did not recognise/);});
test('Azure cancellation details are shown without connection query strings',async()=>{const {sdk}=fakeSdk({recognition:{reason:3,errorDetails:'Unsupported language for pronunciation assessment wss://eastus.stt.speech.microsoft.com/stt?Authorization=Bearer%20secret-token&x=1 SessionId: abc'}});const client=createSpeechClient({loadSdk:async()=>sdk,fetcher:async()=>new Response('token')});await assert.rejects(()=>client.assess({key:'a'.repeat(32),word:words[10],audio:clip()}),e=>{assert.match(e.message,/^Azure could not finish: Unsupported language for pronunciation assessment/);assert.doesNotMatch(e.message,/secret-token|Authorization/);return true;});});
test('rejected key reports the HTTP status',async()=>{const {sdk}=fakeSdk();const client=createSpeechClient({loadSdk:async()=>sdk,fetcher:async()=>new Response('denied',{status:401})});await assert.rejects(()=>client.say({key:'a'.repeat(32),word:words[0]}),/Azure could not finish: Azure rejected the key \(HTTP 401\)/);});
test('a slow Azure answer reports a timeout instead of the generic failure',async()=>{const {sdk}=fakeSdk({hang:true});const client=createSpeechClient({loadSdk:async()=>sdk,fetcher:async()=>new Response('token'),timeoutMs:50});await assert.rejects(()=>client.assess({key:'a'.repeat(32),word:words[10],audio:clip()}),/Azure could not finish: Azure did not answer within 0 seconds|did not answer within/);});
