import test from 'node:test';import assert from 'node:assert/strict';
import {words,pickWord} from '../lib/words.mjs';import {toWav} from '../lib/audio.mjs';import {validateWav,assessmentResult,ssml,readBounded} from '../lib/protocol.mjs';
const tone=()=>new Float32Array(48000).map((_,i)=>Math.sin(i/15)*.1);
test('character count excludes stress and preserves ё',()=>{for(const w of words){assert.equal(w.length,[...w.text].length);assert.equal(w.stress.replaceAll('\u0301',''),w.text);}for(let m=3;m<=10;m++)for(let i=0;i<100;i++){const w=pickWord(m,0);assert.ok(w.length<=m);assert.notEqual(w.id,0);}});
test('WAV mono PCM16 resampled and bounded',()=>{const wav=toWav([tone()],48000);assert.equal(wav.byteLength,32044);assert.equal(validateWav(wav).duration,1);assert.equal(toWav(Array(20).fill(tone()),48000).byteLength,256044);});
test('reject silence, malformed and oversized audio',()=>{assert.throws(()=>validateWav(toWav([new Float32Array(48000)],48000)),/quiet/);assert.throws(()=>validateWav(new ArrayBuffer(10)));assert.throws(()=>validateWav(new ArrayBuffer(300000)));});
test('safe score normalization supports REST and SDK',()=>{for(const nested of [false,true]){let scores={AccuracyScore:88.2};let best={Confidence:.8,...(nested?{PronunciationAssessment:scores}:scores),Words:[]};assert.equal(assessmentResult({RecognitionStatus:'Success',NBest:[best]}).accuracy,88);}for(const n of [NaN,Infinity,-3,101,'90',undefined])assert.equal(assessmentResult({RecognitionStatus:'Success',NBest:[{Confidence:.8,AccuracyScore:n}]}).kind,'uncertain');assert.equal(assessmentResult({RecognitionStatus:'Success',NBest:[{Confidence:.2,AccuracyScore:90}]}).kind,'uncertain');});
test('TTS only supported voice and unchanged pitch',()=>{assert.match(ssml(words[0],true,'Svetlana'),/rate="-20%"/);assert.doesNotMatch(ssml(words[0],true,'Svetlana'),/pitch=/);assert.throws(()=>ssml(words[0],false,'evil'));});
test('read bounds rejects oversize bodies',async()=>{await assert.rejects(()=>readBounded(new Request('https://test',{method:'POST',body:'123456'}),5));});
