"""Ship every Wiktionary record for each dictionary spelling, verbatim, as on-demand shards.

Usage: python scripts/extract-word-details.py /path/to/kaikki-russian.jsonl
Writes public/words/<shard>-<hash>.json.gz (grouped by the first two or three letters of the spelling) and
lib/word-details-manifest.mjs mapping each prefix to its content-hashed file. Nothing is removed
from the records; the app renders the known fields and shows the full record as well.
"""
import collections, gzip, hashlib, json, pathlib, shutil, sys
ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = pathlib.Path(sys.argv[1])
rows = json.loads((ROOT / 'public/dictionary-data.json').read_text())
wanted = {r[0] for r in rows}
by_word = collections.defaultdict(list)
for line in SOURCE.open():
    x = json.loads(line)
    if x.get('word') in wanted:
        by_word[x['word']].append(x)
# Shards are keyed by the first two letters; a prefix whose shard would exceed LIMIT bytes (по…, пр…)
# is split by the first three letters so a first tap never waits for a multi-megabyte download.
LIMIT = 400_000
def size_of(group):
    return len(gzip.compress(json.dumps(group, ensure_ascii=False, separators=(',', ':')).encode(), 6))
shards = collections.defaultdict(dict)
for w, records in by_word.items():
    shards[w[:2]][w] = records
for key in [k for k, g in shards.items() if size_of(g) > LIMIT]:
    for w, records in shards.pop(key).items():
        shards[w[:3]][w] = records
out = ROOT / 'public/words'
shutil.rmtree(out, ignore_errors=True); out.mkdir()
manifest = {}
total = 0
for i, key in enumerate(sorted(shards)):
    payload = json.dumps(shards[key], ensure_ascii=False, separators=(',', ':')).encode()
    data = gzip.compress(payload, 9, mtime=0)
    name = f'{i:04d}-{hashlib.sha256(data).hexdigest()[:16]}.json.gz'
    (out / name).write_bytes(data); total += len(data)
    manifest[key] = '/words/' + name
(ROOT / 'lib/word-details-manifest.mjs').write_text('// Generated by scripts/extract-word-details.py; CC BY-SA 4.0 (see public/dictionary-attribution.json).\nexport default ' + json.dumps({'format': 1, 'records': sum(len(v) for v in by_word.values()), 'spellings': len(by_word), 'shards': manifest}, ensure_ascii=False, separators=(',', ':')) + ';\n')
meta_path = ROOT / 'public/dictionary-attribution.json'
meta = json.loads(meta_path.read_text())
meta['details'] = {'description': 'Every English Wiktionary record (all fields, unmodified) for each dictionary spelling, extracted from the same Kaikki snapshot and shipped in compressed shards under /words/, fetched when a word is tapped.', 'records': sum(len(v) for v in by_word.values()), 'spellings': len(by_word), 'shards': len(manifest), 'bytes': total}
meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2) + '\n')
print(f'{len(by_word)} spellings, {meta["details"]["records"]} records, {len(manifest)} shards, {total/1e6:.1f} MB; missing: {len(wanted - set(by_word))}')
sizes = sorted((p.stat().st_size for p in out.iterdir()), reverse=True)
print('largest shards KB:', [s // 1024 for s in sizes[:5]], 'median KB:', sizes[len(sizes)//2] // 1024)
