"""Ship every Wiktionary record for each dictionary spelling, verbatim, as on-demand shards, plus a
forms index (inflected form -> dictionary spellings) so a long-pressed form can load its lemma.

Usage: python scripts/extract-word-details.py /path/to/kaikki-russian.jsonl
Writes public/words/<shard>-<hash>.json.gz (grouped by the first two or three letters of the spelling) and
lib/word-details-manifest.mjs mapping each prefix to its content-hashed file. Nothing is removed
from the records; the app renders the known fields and shows the full record as well.
"""
import collections, gzip, hashlib, json, pathlib, shutil, sys
ROOT = pathlib.Path(__file__).resolve().parents[1]
SOURCE = pathlib.Path(sys.argv[1])
rows = json.loads((ROOT / 'public/dictionary-data.json').read_text())
wanted = {r[0] for r in rows}
by_word = collections.defaultdict(list)
for line in SOURCE.open():
    x = json.loads(line)
    if x.get('word') in wanted:
        by_word[x['word']].append(x)
# Shards are keyed by the first two letters; a prefix whose shard would exceed LIMIT bytes (по…, пр…)
# is split by the first three letters so a first tap never waits for a multi-megabyte download.
LIMIT = 400_000
def size_of(group):
    return len(gzip.compress(json.dumps(group, ensure_ascii=False, separators=(',', ':')).encode(), 6))
shards = collections.defaultdict(dict)
for w, records in by_word.items():
    shards[w[:2]][w] = records
for key in [k for k, g in shards.items() if size_of(g) > LIMIT]:
    for w, records in shards.pop(key).items():
        shards[w[:3]][w] = records
out = ROOT / 'public/words'
shutil.rmtree(out, ignore_errors=True); out.mkdir()
manifest = {}
total = 0
for i, key in enumerate(sorted(shards)):
    payload = json.dumps(shards[key], ensure_ascii=False, separators=(',', ':')).encode()
    data = gzip.compress(payload, 9, mtime=0)
    name = f'{i:04d}-{hashlib.sha256(data).hexdigest()[:16]}.json.gz'
    (out / name).write_bytes(data); total += len(data)
    manifest[key] = '/words/' + name
(ROOT / 'lib/word-details-manifest.mjs').write_text('// Generated by scripts/extract-word-details.py; CC BY-SA 4.0 (see public/dictionary-attribution.json).\nexport default ' + json.dumps({'format': 1, 'records': sum(len(v) for v in by_word.values()), 'spellings': len(by_word), 'shards': manifest}, ensure_ascii=False, separators=(',', ':')) + ';\n')
# Forms index: every Cyrillic inflected form of a dictionary word -> the spellings it belongs to.
import re
CYR = re.compile('^[а-яё-]+$')
forms_of = collections.defaultdict(set)
for w, records in by_word.items():
    for r in records:
        for f in r.get('forms', []):
            form = f.get('form', '').replace('\u0301', '').lower()
            if CYR.match(form) and form != w and 'canonical' not in f.get('tags', []) and not re.search('table|template', ' '.join(f.get('tags', []))):
                forms_of[form].add(w)
fshards = collections.defaultdict(dict)
for form, lemmas in forms_of.items():
    fshards[form[:2]][form] = sorted(lemmas)
for key in [k for k, g in fshards.items() if size_of(g) > LIMIT]:
    for form, lemmas in fshards.pop(key).items():
        fshards[form[:3]][form] = lemmas
fout = ROOT / 'public/forms'
shutil.rmtree(fout, ignore_errors=True); fout.mkdir()
fmanifest = {}; ftotal = 0
for i, key in enumerate(sorted(fshards)):
    data = gzip.compress(json.dumps(fshards[key], ensure_ascii=False, separators=(',', ':')).encode(), 9, mtime=0)
    name = f'{i:04d}-{hashlib.sha256(data).hexdigest()[:16]}.json.gz'
    (fout / name).write_bytes(data); ftotal += len(data)
    fmanifest[key] = '/forms/' + name
(ROOT / 'lib/word-forms-manifest.mjs').write_text('// Generated by scripts/extract-word-details.py; CC BY-SA 4.0 (see public/dictionary-attribution.json).\nexport default ' + json.dumps({'format': 1, 'forms': len(forms_of), 'shards': fmanifest}, ensure_ascii=False, separators=(',', ':')) + ';\n')
print(f'forms index: {len(forms_of)} forms, {len(fmanifest)} shards, {ftotal/1e6:.1f} MB')
meta_path = ROOT / 'public/dictionary-attribution.json'
meta = json.loads(meta_path.read_text())
meta['forms'] = {'description': 'Index of every inflected form of a dictionary word (stress marks removed) to its dictionary spellings, from the same Wiktionary records, in compressed shards under /forms/; used when a form is long-pressed in the word panel.', 'forms': len(forms_of), 'shards': len(fmanifest), 'bytes': ftotal}
meta['details'] = {'description': 'Every English Wiktionary record (all fields, unmodified) for each dictionary spelling, extracted from the same Kaikki snapshot and shipped in compressed shards under /words/, fetched when a word is tapped.', 'records': sum(len(v) for v in by_word.values()), 'spellings': len(by_word), 'shards': len(manifest), 'bytes': total}
meta_path.write_text(json.dumps(meta, ensure_ascii=False, indent=2) + '\n')
print(f'{len(by_word)} spellings, {meta["details"]["records"]} records, {len(manifest)} shards, {total/1e6:.1f} MB; missing: {len(wanted - set(by_word))}')
sizes = sorted((p.stat().st_size for p in out.iterdir()), reverse=True)
print('largest shards KB:', [s // 1024 for s in sizes[:5]], 'median KB:', sizes[len(sizes)//2] // 1024)
